<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg><img src=Fri_Jul_02_11_12_47_IST_2021.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<br>Verification failure : expected [1] but found [2]<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg><img src=Fri_Jul_02_11_12_47_IST_2021.jpg height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[adding customer message ]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="24346" started-at="2021-07-02T05:42:37Z" finished-at="2021-07-02T05:43:02Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="9734" started-at="2021-07-02T05:42:37Z" finished-at="2021-07-02T05:42:47Z">
      <class name="com.w2a.testcases.LoginTest">
        <test-method status="FAIL" signature="loginasBankManahger()[pri:0, instance:com.w2a.testcases.LoginTest@74e52ef6]" name="loginasBankManahger" duration-ms="9143" started-at="2021-07-02T11:12:37Z" finished-at="2021-07-02T11:12:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	intentially failing the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	intentially failing the test
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.w2a.testcases.LoginTest.loginasBankManahger(LoginTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg><img src=Fri_Jul_02_11_12_47_IST_2021.jpg height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginasBankManahger -->
        <test-method status="PASS" signature="loginasnewbankmanaer()[pri:0, instance:com.w2a.testcases.LoginTest@74e52ef6]" name="loginasnewbankmanaer" duration-ms="119" started-at="2021-07-02T11:12:47Z" finished-at="2021-07-02T11:12:47Z">
          <reporter-output>
            <line>
              <![CDATA[<br>Verification failure : expected [1] but found [2]<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Fri_Jul_02_11_12_47_IST_2021.jpg><img src=Fri_Jul_02_11_12_47_IST_2021.jpg height=200 width=200></img></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginasnewbankmanaer -->
      </class> <!-- com.w2a.testcases.LoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add customer Test" duration-ms="14592" started-at="2021-07-02T05:42:47Z" finished-at="2021-07-02T05:43:02Z">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@2aceadd4]" name="setUp" is-config="true" duration-ms="5818" started-at="2021-07-02T11:12:32Z" finished-at="2021-07-02T11:12:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.AddCustomerTest@2aceadd4]" name="addCustomerTest" duration-ms="14530" started-at="2021-07-02T11:12:47Z" data-provider="dp" finished-at="2021-07-02T11:13:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{postcode=1.0, lastname=1.0, firstname=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[adding customer message ]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@2aceadd4]" name="tearDown" is-config="true" duration-ms="717" started-at="2021-07-02T11:13:02Z" finished-at="2021-07-02T11:13:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
